# Generated by Django 3.1.7 on 2021-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210305_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Phone', models.IntegerField(default='', max_length=10)),
                ('Message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
