# Generated by Django 3.1.7 on 2021-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210307_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Phone', models.IntegerField(default='')),
                ('Address', models.CharField(default='', max_length=300)),
                ('State', models.CharField(default='', max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('Pincode', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.CharField(default=123, max_length=50),
        ),
    ]
