# Generated by Django 3.1.7 on 2021-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210311_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(default='', max_length=21),
        ),
    ]
