# Generated by Django 3.1.7 on 2021-03-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210311_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_id',
        ),
    ]
